### PR TITLE
[ST-1759] convert to Tailwind

### PR DESCRIPTION
**Pull request by christophermlne**
## Changes
converted template to tailwind

## Ticket
[ST-1759]

## Testing Instructions

- [ ] TODO

---

## Related PRs (Optional)

- 

---

### Author Checklist

- Author wrote tests for the changes
- Selected a team in the Reviewers drop-down to auto-assign reviewers
- Selected one of the reviewers as the Assignee to be the primary reviewer
- (Optional) Explained any new third-party additions

#### For the Reviewer(s)

- Read and understood the code change.
- Verified the changes are tested.
- Verified the code is feature flagged (if needed).

#### For the Assignee (all of the above plus...)

- Ran the code locally or on a staging server and verified it works.
- Approved all Percy changes (if needed)

[ST-1759]: https://precisionnutrition.atlassian.net/browse/ST-1759

### CODE REVIEW

**Review by jherdman — APPROVED** [review]

**Comment by jherdman** [comment]
Would you be amenable to opening a PR to fix CI? You can probably get away with copying the Github Action config for the FCR and tweak it accordingly.

**Comment by christophermlne** [comment]
> Would you be amenable to opening a PR to fix CI? You can probably get away with copying the Github Action config for the FCR and tweak it accordingly.

will do

**Comment by jherdman** [comment]
If you rebase CI ought to go green.

**Pull request merged**
